### PR TITLE
Update deps of grunt-zanata-js

### PR DESCRIPTION
**Pull request by tagoh**
to fix an issue not working after updating to nodejs 4.4

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by jasonmadigan** [comment]
thanks @tagoh - do you have some steps/commands in mind that could be used to verify/test this?

**Comment by tagoh** [comment]
@jasonmadigan sorry, should mention that. for pushing, "grunt potupload" and for pulling "grunt zanata:pull" would works for testing.

**Comment by david-martin** [comment]
@tagoh The `zanata:pull` task gives output as below
```
[dmartin@rollins-tp fh-fhc]$ grunt zanata:pull
Running "zanata:pull" (zanata) task
>> Downloaded into po/ja.po

Done, without errors.


Execution Time (2016-09-08 16:08:33 UTC)
loading tasks      992ms  ▇▇ 1%
zanata:pull     1m 12.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 1m 13.8s

[dmartin@rollins-tp fh-fhc]$ git status
On branch update-zanata
Your branch is up-to-date with 'tagoh/update-zanata'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	po/etag-cache.json
	po/ja.po

nothing added to commit but untracked files present (use "git add" to track)
```
Does this look like expected output to you?

The `potupload` tasks gives an unauthorized error, but I guess this is OK as I don't want to actually upload anything without knowing what I'm doing

```
[dmartin@rollins-tp fh-fhc]$ grunt potupload
Running "jsxgettext:pot" (jsxgettext) task

Running "zanata:push" (zanata) task
>> Error: Unauthorized operation
Warning: Task "zanata:push" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2016-09-08 16:12:09 UTC)
loading tasks      1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 37%
jsxgettext:pot  420ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 15%
zanata:push      1.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 48%
Total 2.8s
```

With the above commands wired up OK (and probably working OK), and the passing CI build, I'm happy to merge this.
Needs a rebase from master first

**Comment by tagoh** [comment]
@david-martin Thank you for review. updated.

**Pull request merged**
