### PR TITLE
RHMAP-3132 - FHC general improvements.

### PR DESCRIPTION
**Pull request by wtrocki**
General improvements required to use `fh:dist` grunt target. 

#### What was done
 - General codestyle fixes and small refactoring
 - Fixes for errors in command completion.
 - Removed stale code for formatting tables.
 - Fixed package.json format

### CODE REVIEW

**Comment by fheng-build-servers** [comment]
@jasonmadigan @cianclarke please review this PR.

**Comment by fheng-build-servers** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by wei-lee** [comment]
Reviewed.

**Comment by wtrocki** [comment]
Thanks. Merging changes into master.

**Pull request merged**
