### PR TITLE
Add a shrinkwrap file for npm

### PR DESCRIPTION
**Pull request by grdryn**

### CODE REVIEW

**Comment by fheng-build-servers** [comment]
[SUCCESS] A build relating to [Ticket #FH-137](https://issues.jboss.org/browse/FH-137) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/15/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/15/)

**Comment by jasonmadigan** [comment]
Reviewed.

**Comment by fheng-build-servers** [comment]
[SUCCESS] A build relating to [Ticket #FH-137](https://issues.jboss.org/browse/FH-137) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/16/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/16/)

**Comment by grdryn** [comment]
Updated to remove change to BUILD-NUMBER.

**Comment by jasonmadigan** [comment]
Merging as agreed.

**Pull request merged**
