### PR TITLE
New CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by davidffrench**
Added a contributing file to make it easier for the community to make changes and submit PRs. 

I think this is a good starting place, another good section in the contributing file would be how to raise issues. We can have internal members use JIRA but what about outside community members, is raising issues through GitHub sufficient or is there another process that ye had in mind?

No need for a version bump in my opinion since this change does not need a new release to npm. 

@david-martin

### CODE REVIEW

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by davidffrench** [comment]
I have just seen https://issues.jboss.org/browse/RHMAP-11227 which could conflict with my Contributing guide for fhc. There might be some ideas from my own contributing guide that could be included in the other generic one.

@wtrocki , @david-martin any thoughts?

**Comment by david-martin** [comment]
@wtrocki I wonder if each repo had a link to a general contributing guide (which included things like eslint, tests, PR workflow), and also included extra contributing guidelines if necessary?

**Comment by wtrocki** [comment]
@davidffrench @david-martin  I would include some of the changes into general contributing guide that would be applied to each repo. Contributing guides tend to be mostly generic and inform users about contribution process. Technical details like how to setup environment are part of documentation.

I think it would be easier for us to maintain single generic contribution guide with links to our code style rules etc. See https://github.com/fheng/best_practice

If we choose to provide separate guide for each repo then we may hit following problems:
- Outdated recommendations
- Separate style - no global overview. 
- No way to automatically apply guide to new repositories

Having something generic would be very useful than nothing. We can have separate versions for some different projects like RainCacher.

**Comment by davidffrench** [comment]
@wtrocki I agree with you on the problems with having a separate contributing guide for each repo. 

In an ideal world, each repo would have a contributing guide that is 90%+ the same as all other repos contributing guides, the generic parts can be kept up to date from a central guide so they don't become stale or inconsistent with each other. While also having 10% of the guide for project specific steps without having to look at any other documentation to know how to contribute. In an ideal world though.

In my opinion, If the above is not possible, I am definitely leaning towards your suggestion of a consistent guide across all repos. My only concern is potentially losing some contributors if they run into any problems setting up a project and run in project specific problems that are not in the contributing guide but i feel like this number will be small if it exists at all.

**Comment by wtrocki** [comment]
@davidffrench How about having generic CONTRIBUTING.md with link to CUSTOMIZING.md that may contain some more targeted informations and links. 
Example: https://github.com/eclipse/che/blob/master/CUSTOMIZING.md

**Comment by davidffrench** [comment]
Hey @wtrocki. Sorry for the late reply. Another guide called CUSTOMIZING would work well in my opinion.

**Comment by wtrocki** [comment]
Going to close PR and create new one for general contribution guide and customizing contribution guide.

**Pull request closed without merging**
