### PR TITLE
special character check for app title to tie in with millicore and fh-ng...

### PR DESCRIPTION
**Pull request by grahamhillis**
...ui changes already committed

### CODE REVIEW

**Comment by fheng-build-servers** [comment]
[SUCCESS] A build relating to [Ticket #FHMAP-68](https://issues.jboss.org/browse/FHMAP-68) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/8/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/8/)

**Comment by grahamhillis** [comment]
@wei-lee @david-martin @jasonmadigan review/comment please? This should tie up the fix across millicore, fh-ngui and fh-fhc for app create?

**Comment by wei-lee** [comment]
looks fine. But what about app updates? Is there validation on the app title as well?

TBH, we can just validate the app title on the server side (millicore) - fhc just need to show the error message.

**Comment by david-martin** [comment]
looks ok.
Do we want to do the validation here though at app create time, or in millicore in the app create endpoint?

**Comment by grahamhillis** [comment]
As it stands, fh-ngui client-side validation prevents moving forward with creation if special characters in the name (as unique name check does), if I add this validation to the update function in fhc then FHC client will prevent in this fashion also. The code in millicore replaces any special chars in the name before substitution in xml config file to prevent build errors. It's a simple check, why make a full request to catch error?

**Comment by david-martin** [comment]
for maintenance purposes, best to keep the validation in 1 place i.e. millicore endpoints for app create & update.

We should keep the find/replace logic at build time in millicore (as its already in place and will catch existing apps).
We should also validate the app name at create/update time in millicore.

**Comment by grahamhillis** [comment]
Closing pull request as code changes only required in millicore

**Pull request closed without merging**
