### PR TITLE
FH-3824 - fhc services make all result commands respect json parameter

### PR DESCRIPTION
**Pull request by camilamacedo86**
JIRA: https://issues.jboss.org/browse/FH-3824

Motivation: It is just an improvement and don't will solve the following issue it is another PR.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@mmusil Could you check and review this one?

**Comment by mmusil** [comment]
@camilamacedo86 `fhc services create --title="mmusil_FHC"`
```
fhc ERR! cb() never called!
fhc ERR!  
fhc Command executed with error
/home/mmusil/.nvm/versions/node/v4.4.7/lib/node_modules/fh-fhc/lib/cmd/fh3/services/create.js:46
    fhc.templates.services({ id:params.template || "new-service", json:true }, function(err, template) {
                  ^

TypeError: fhc.templates.services is not a function
    at Object.module.exports.customCmd (/home/mmusil/.nvm/versions/node/v4.4.7/lib/node_modules/fh-fhc/lib/cmd/fh3/services/create.js:46:19)
    at custom (/home/mmusil/.nvm/versions/node/v4.4.7/lib/node_modules/fh-fhc/lib/genericCommand.js:111:19)
    at fn (/home/mmusil/.nvm/versions/node/v4.4.7/lib/node_modules/fh-fhc/node_modules/async/lib/async.js:579:34)
    at Immediate._onImmediate (/home/mmusil/.nvm/versions/node/v4.4.7/lib/node_modules/fh-fhc/node_modules/async/lib/async.js:495:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
I think, that's not exactly what we wanted 🤔 😁

**Comment by camilamacedo86** [comment]
@mmusil I will check it thank you for the test.

**Comment by camilamacedo86** [comment]
@mmusil the issues faced by you is not related to this PR. It is a bug caused by a change into the templates which is into the PR #369. The fix PR for that is https://github.com/feedhenry/fh-fhc/pull/394.

**Pull request closed without merging**
