### PR TITLE
update node js engines

### PR DESCRIPTION
**Pull request by maleck13**
@kpiwko updated node engine

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by maleck13** [comment]
@grdryn quick review

**Comment by maleck13** [comment]
@grdryn thanks. It was causing an issue when a user installed fhc with 4.6 of nodejs which is the LTS. As the engine was specified as 4.4 it would give out during the install.

**Comment by grdryn** [comment]
> It was causing an issue when a user installed fhc with 4.6 of nodejs which is the LTS. As the engine was specified as 4.4 it would give out during the install.

@maleck13 Ah right. In that case, should we look to change it to `"node": ">=0.8 <= 4"`, in case there's a 4.7+ (unlikely) and we have the same problem?

Also, extremely soon (hours or days, I'd say), nodejs 0.10 will be EOL, version 4 will go into maintenance, and version 6 will become the LTS. At that point, I think we should look to change it to `"node": ">=4"`. What do you think?

**Comment by maleck13** [comment]
@grdryn agree we should change it once 0.10 is EOL. Good point about the 4.7 I will update and change my deployment note

**Comment by kpiwko** [comment]
@grdryn good point. @maleck13 created and triggered job here - https://mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhmap3-uart-chrome-nodejs46-zeta/

**Comment by kpiwko** [comment]
Have not seen any fhc related issue at
https://mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/All/job/rhmap3-uart-chrome-nodejs46-zeta/2/consoleFull
- but the truth is the number of failures has grown up. Might be related to
@asaleh 's cleanup of env performance in the same period though.

**Pull request merged**
