### PR TITLE
Remove FH3.md file because it is outdated

### PR DESCRIPTION
**Pull request by camilamacedo86**

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@pb82 I believe that all information here is not so long required. What do you think? What information do you think here that we should add into the ReadMe?

**Comment by camilamacedo86** [comment]
Hi @pb82, it is here a while. Please, could you check this one? The information in this file shows outdated and not required anymore. Could we move forward with this one?

**Comment by camilamacedo86** [comment]
@davidffrench Yes, the information that is not outdated and useful it is. The commands are possible to be taken via fhc command and so long is not required be a doc outdated with them. 

Please, could you review and if you agree: could you approve in order to allow me do the rebase with the master, bump version and merge it?

**Comment by davidffrench** [comment]
Hey @camilamacedo86 , Please rebase locally and force push to the branch. Once this is done and it is not outdated anymore, i will approve.

**Comment by camilamacedo86** [comment]
@davidffrench done 👍

**Pull request merged**
