### PR TITLE
FH-3411 - fh-fhc upload app binary does not use proxy setting

### PR DESCRIPTION
**Pull request by camilamacedo86**
JIRA: https://issues.jboss.org/browse/FH-3411

Following the local tests performed.

**Tests with proxy**

1. Set the proxy
`$./bin/fhc.js fhcfg set proxy https://127.0.0.1:8888`

2. Check if is there the proxy:
`./bin/fhc.js fhcfg list`

screen shot 2017-05-24 at 2 16 34 pm

3. Call the command to upload the binary
`$./bin/fhc.js admin-storeitems uploadbinary 5w477lfgy3jrnovri7gctsb7 android ~/Desktop/Push.apk`
 
4. Validate if the binary file was upload.

screen shot 2017-05-24 at 2 17 57 pm

5. Debug the command to check if is taken the correct value for the proxy and using it. 

screen shot 2017-05-24 at 2 12 15 pm

screen shot 2017-05-24 at 2 20 08 pm

**Tests without proxy**

1.To remove the proxy.
`./bin/fhc.js fhcfg set proxy " "`

2.To check if the proxy value was removed
`./bin/fhc.js fhcfg list`

screen shot 2017-05-24 at 5 56 13 pm

3.To execute the command
`./bin/fhc.js admin-storeitems uploadbinary 5w477lfgy3jrnovri7gctsb7 android ~/Desktop/Push.apk`

screen shot 2017-05-24 at 6 01 17 pm

4.Validate it in the studio.

screen shot 2017-05-24 at 6 01 42 pm

### CODE REVIEW

**Comment by mmurphy** [comment]
@camilamacedo86 have you tested it to verify that the proxy is used and working for file uploads?

**Comment by camilamacedo86** [comment]
Hi @mmurphy,

Yes, I did. 

Following the local tests performed.

To set the proxy
`$./bin/fhc.js fhcfg set proxy https://127.0.0.1:8888`

To check if is there the proxy:
`./bin/fhc.js fhcfg list`

screen shot 2017-05-24 at 2 16 34 pm

To do the Rest
`$./bin/fhc.js admin-storeitems uploadbinary 5w477lfgy3jrnovri7gctsb7 android ~/Desktop/Push.apk`
 
To validate if the binary file was upload.

screen shot 2017-05-24 at 2 17 57 pm

Debug to check if is taken the correctly value for proxy. 

screen shot 2017-05-24 at 2 12 15 pm

screen shot 2017-05-24 at 2 20 08 pm

**Comment by mmurphy** [comment]
@camilamacedo86 Does the local machine that you tested on *require* a proxy, for example, would the old code that didn't use the proxy also still upload the file?

**Comment by camilamacedo86** [comment]
@mmurphy . Tks for the validation. It I didn't test before, however, it is working as expected. I will centralize all tests in the body of the first comment.

**Comment by camilamacedo86** [comment]
We checked it together. This change don't fixed the issue and it is probably be faced for all commands that are using this method to upload files.  The info was added into the JIRA a new PR will be made. 

c/c @mmurphy

**Pull request closed without merging**
