### PR TITLE
Fixing git prop set

### PR DESCRIPTION
**Pull request by jasonmadigan**
`fhc git props` & `fhc git set` have been broken with a while, this patches and fixes the commands.

Some commands to test with below.

Reading git props for an app:

```
fhc git props 6magpwla4zuxssywj77u6o2x
```

Setting a default branch for an app:

```
fhc git set 6magpwla4zuxssywj77u6o2x branch master
```

### CODE REVIEW

**Comment by fh-qube** [comment]
SonarQube analysis reported 5 issues:
* MINOR 5 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Reformat the code to have only one statement per line.](https://github.com/feedhenry/fh-fhc/blob/8d6e620158ee47ed046032978e6d787f79323326/lib/cmd/common/git.js#L110) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AOneStatementPerLine)
* MINOR [Reformat the code to have only one statement per line.](https://github.com/feedhenry/fh-fhc/blob/8d6e620158ee47ed046032978e6d787f79323326/lib/cmd/common/git.js#L107) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AOneStatementPerLine)
* MINOR [Reformat the code to have only one statement per line.](https://github.com/feedhenry/fh-fhc/blob/8d6e620158ee47ed046032978e6d787f79323326/lib/cmd/common/git.js#L108) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AOneStatementPerLine)
* MINOR [Reformat the code to have only one statement per line.](https://github.com/feedhenry/fh-fhc/blob/8d6e620158ee47ed046032978e6d787f79323326/lib/common.js#L898) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AOneStatementPerLine)

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by jasonmadigan** [comment]
@david-martin here's one for ya

**Comment by david-martin** [comment]
@jasonmadigan  Tested locally. Looks to behave as expected.
```
[dmartin@rollins-tp fh-fhc]$ fhc git props 3wn3ny6yewlvwwjg3zzyd4ca

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃ Url                                                           ┃ Branch ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ git@git.tom.redhatmobile.com:coneill/dmtest01-Cordova-App.git ┃ master ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━┛

[dmartin@rollins-tp fh-fhc]$ fhc git set 3wn3ny6yewlvwwjg3zzyd4ca branch test
Property set ok

[dmartin@rollins-tp fh-fhc]$ fhc git props 3wn3ny6yewlvwwjg3zzyd4ca

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃ Url                                                           ┃ Branch   ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ git@git.tom.redhatmobile.com:coneill/dmtest01-Cordova-App.git ┃ test     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━┛
```

**NOTE** had to manually do a 'git pull' in the studio after changing branch.

**Comment by jasonmadigan** [comment]
thanks @david-martin, merging

**Pull request merged**
