### PR TITLE
Updates Changelog 

### PR DESCRIPTION
**Pull request by damienomurchu**
Update changelog as per [RHMAP-19216](https://issues.jboss.org/browse/RHMAP-19216). 

Changes:
- CHANGELOG.md updated
- note to update CHANGELOG.md added to README.md
- note re: commit message standard added to README.md
- version bumped to 4.2.1 (from 4.2.0)

### CODE REVIEW

**Comment by davidffrench** [comment]
Fantastic work again @damienomurchu. I know this is still a WIP, two comments so far and i will review again once you it is finished.

**Comment by damienomurchu** [comment]
@davidffrench @austincunningham @matskiv @grdryn @camilamacedo86 - pinging for review

**Comment by camilamacedo86** [comment]
@damienomurchu fantastic contribution 👍  Just few concerns/questions.

* Should not better we add the ID of the JIRA in the standard? With the JIRAID is possible check the details of the change.  Also, for opensource projects all users are able to check the JIRAs and should create a task or contribute with some already maped need there. 

* Is this nomenclature/standard definied for all projects? ( E.g fix(parsing): `text msg`)

**Comment by damienomurchu** [comment]
@camilamacedo86 thanks, and good points. My own thoughts:
- JIRA ID in changelog a great idea if the JIRA's are open and anyone can access them (FH-xxxxx are accessible to all, but RHMAP-xxxxx are not, am I right here?)
- yes, a commit message convention (as per the one noted in README) is something we are looking to introduce for various reasons (good, albeit non-open, doc [here](https://docs.google.com/document/d/1maQkhz0kwm7HnJ_a-wI1OSHslkpgjqSkg0_xsByHzDw/edit#heading=h.o5tvncooq8ee)). We've already recently introduced this format in fh-mbaas-api & will look to roll out the convention to other repos. 
- re: commit message format, I think including the JIRA ID in the commit message is a good idea, and would feel the optional body in the commit message (as per below) would be the best place for it for a few reasons:
  - keeps the first line of the commit message clean & descriptive (without a need to dive into JIRAs for immediate detail on the change)
  - allows us to use standard changelog tools (without too much modification) to auto-generate changelogs from the commit history 
  - retains the link to the JIRA

_*Commit w/ JIRA in body of commit:*_
``` 
git commit -a -m "feat(new-parser): introduces a new parsing library
FH-12345: Add new parsing functionality to fh-xyz"

**Comment by damienomurchu** [comment]
@camilamacedo86 sounds good, will add a note re adding the JIRA ID

**Pull request merged**
