### PR TITLE
[RHMAP-5022] Fix argsToPayload regression

### PR DESCRIPTION
**Pull request by paolobueno**
Quick fix for bug introduced in the refactoring for this issue.

Tested it manually against `eng1` to confirm it reproduces correct behavior from <2.4.1

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by paolobueno** [comment]
ping @wtrocki @wei-lee @vchepeli

**Comment by pb82** [comment]
LGTM

**Comment by wei-lee** [comment]
LGTM

**Comment by paolobueno** [comment]
I reduced the commit to parity, it had a `JSON.stringify` call on object params that is actually related to RHMAP-4633

**Pull request merged**
