### PR TITLE
Add fh DB commands

### PR DESCRIPTION
**Pull request by cianclarke**

### CODE REVIEW

**Comment by maleck13** [comment]
@cianclarke I am really not sure this is something we want to actually be part of fhc. This seems like it would be more at home in a dedicated export import tool. Also as we saw recently apps can have dbs of 70GB + not sure we would want to try and send things like that over http to the app.

**Comment by cianclarke** [comment]
@maleck13 We're already doing this in the studio though - we expose import and export operations in the UI, so really just fulfilling the goal of FHC parity with the UI (is that still a thing?)

**Comment by maleck13** [comment]
@cianclarke The fact that we do this via the UI is a bit disturbing to me also. If anything I would look to remove that functionality and provide a better solution. Direct access to the mongo instance for example. I still don't think this should end up as part of fhc

**Comment by cianclarke** [comment]
@maleck13 Not sure I agree - being able to export the DB has proved a real lifesaver in a number of scenarios recently, it seems a very useful feature. 
Sure, in the rare edge case of the 70gb database it's a problem - but the vast majority of people using Mongo have much smaller datasets. 
Without this functionality, the only way of exporting or importing large datasets is to write custom cloud code with an endpoint to do - well, exactly what the `/mbaas/db` endpoints do. 

Meanwhile, are we even talking about direct MongoDB access as an option? It'd be even more helpful, but it'd need to span legacy domains too..

**Comment by maleck13** [comment]
@cianclarke While it might be a useful feature. It isn't the correct solution to the problem. Going through the cloud app (that might well be a production app) and pulling in potentially huge data sets shouldn't be something we look to encourage (IMHO). I would much rather see this at the platform level or as stated give access in someway directly to mongo so imports and exports can be done with the correct tools for the job

**Comment by wtrocki** [comment]
@cianclarke basing on comments I see that your change may be part of separate tool. Going to close PR as there was no activity for long time.

**Pull request closed without merging**
