### PR TITLE
 ✨  update fhc build to work with self-managed build farm. Also

### PR DESCRIPTION
**Pull request by wei-lee**
generate PR code

## Motive

Small changes required to get fhc build to work with self-managed build farm.

## Changes

1. Correctly resolve the url of artifacts and print them out
2. Print out QR code.

## Verification

* fhc build should continue to work with a cluster that is using the SAAS build farm
* try fhc build again with this project in OSM4: https://osm4-rhmap.osm4.skunkhenry.com/#projects/xmd2inzuf5kakpmvetwtlku4/apps. It should work as well.

### CODE REVIEW

**Comment by fh-qube** [comment]
SonarQube analysis reported 2 issues:
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Function has a complexity of 23 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/a79d5d04a78df79e079f71d489d6da7554c47aab/lib/cmd/common/build.js#L194) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
* MINOR [Function has a complexity of 24 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/a79d5d04a78df79e079f71d489d6da7554c47aab/lib/cmd/common/build.js#L192) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

**Comment by aliok** [comment]
All good 👍 

I executed `fhc build` for that application:

```
fhc build project=xmd2inzuf5kakpmvetwtlku4 app=xmd2in2athbzbudk2hd4liyr destination=android cloud_app=xmd2in2l3pi32gzphn4nttcd environment=dev tag=0.0.25
.......................................................................
Download URL: https://osm4-rhmap.osm4.skunkhenry.com/box/api/artifacts/download/WLTest-Helloworld-Native-Android-Gradle-App_xmd2in2athbzbudk2hd4liyr/23/app-debug.apk?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c
OTA URL: https://osm4-rhmap.osm4.skunkhenry.com/box/api/artifacts/ota/67f91c73-f44c-4ff1-8ffa-5cc925166f5e?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▄▄██▄█▄█▀█▄▀ ▀ ▀▄▀ ▄▄▄▄ ▄█▀▄█ ▄▄▄▄▄ █
█ █   █ █▀▀▀█▀▄▄▄▀ ▀▄▀▀▀█▀▄█▄▄▀▄▄▄▄█ ▀█ █   █ █
█ █▄▄▄█ █▀▄ ▄▄▀ ▄▀ ▀▄ ▄▄▄ ▀▀ █▄▄█▀▀▄▄▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀▄█ █ █▄█ ▀ █▄█ ▀ ▀ █▄█ █ ▀ █▄▄▄▄▄▄▄█
█▄▄  ▄█▄ ▄▀ ▀▀▄▄▄▀▄▄  ▄▄ ▄ ▄█▀▀ ▄▀▄▄█▀▄█▄█▄█ ▀█
█ ██▀▀▀▄ █  █▄ ▄▄ ▄ ▄▄▄██▄▄▄█ ▀▀  ▄▄█ ▄ █ ▀ ▄██
█▄▄▄▀▀▀▄▄▄▄█ █▄▀▀▄▄▄█▀ ▄ ▄ █▄██ ██▀█▄▀▄█▄▀█▀ ▀█
█▀▀  ▀█▄██▀ ▀█▀█▀▄▄▄█▄▀█  █ ▀▀ ▀▄▀█ ▀▀ ▄ ▀▀ ▀██
█▀▄  █▄▄██▄▀▄▄▀█ █▀▄▄▄▀ ▀▄██▄█   ██▄ ▀███▀ ▀  █
██▄  █▄▄▀▄▄▀█▄▄▀▀▄▀ ▄▄███▄▀▄▀ ▀▀ ▀█ ▄ █▄ ▀▀▀▄██
█ █▄█ ▄▄▄ ▄▀▀▄▀▀▄▄█▄▀ ▄▄▄ ▄█▀█▀▀▀██▄▀ ▄▄▄ █▀▄▀█
█▀▀   █▄█   ▀ ▄ ▀█▄ █ █▄█    ▀▀█  ▀▄▄ █▄█ ▄▀▀██
█▀▄█  ▄▄  ▄█▄ ▄▄▄▄▄▄    ▄  ▄█▀▀▀ ▀█▄▀▄▄ ▄▄ ▀▀▀█
█▀██▄▀▄▄▄▄▄ ▄ ▄█▄█ ██▀ ▀▀▀▀▄█  ▀▀ ▄▄▀▄▀▀▀▄▀▀▄██
██▄▀█ ▄▄▄ ▀▀▀▀▀▀▀▄▀▄▀▀▀▀ █ █▄▀▄ █▀▄███ ▄█▄██▀ █
██▄▀ ▀▄▄▀▀▄ ▀ ▀█▀▀▄▄██▀▀▄▀█▄ ▀▄▀▄ ▄  ▀ ▀█ █▀█▀█
█ ██▀▀ ▄▄ ▀ ▀▄▀█▀▄▄▄  ▀▀▄▄ ██▀▀▀ ▀▀█▀▄ █▄▄█▀▄▀█
██▀▀▀ █▄ ▄ █▀█▄█▀▄▄▄▀▄███▀▄▄▄▀ ▀█▀█ ▀▄▀▀██▄ ▄██
█▄██▄▄█▄█ ▄▀▄▀▄▀▀▄▀▄▀ ▄▄▄ ▄█ ██  ██▄█ ▄▄▄ ▀██▀█
█ ▄▄▄▄▄ █▄██ ▄▄ ▄▄▀ ▄ █▄█ ▄▄▀▀▄█ ▀▄▄█ █▄█ ▄▀▄▀█
█ █   █ █ ▄█▄ ▄▄▀▄▀▄█ ▄▄  ▀█▀▀▄ ▄▀ █ ▄▄▄  ▀█ ██
█ █▄▄▄█ █ ██▄ ▀▀▀▄ ▄█▀ ▄▀█▀▄▀ ██▄   ▀ ▀▄█▀▄ █▄█
█▄▄▄▄▄▄▄█▄▄█████▄▄▄▄▄████▄████▄▄▄██▄█▄█▄█▄▄█▄██

```


Downloading the artifacts using wget was successful:
```
ali@Alis-MacBook-Pro:/tmp$ wget https://osm4-rhmap.osm4.skunkhenry.com/box/api/artifacts/download/WLTest-Helloworld-Native-Android-Gradle-App_xmd2in2athbzbudk2hd4liyr/23/app-debug.apk?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c
--2017-08-02 12:05:33--  https://osm4-rhmap.osm4.skunkhenry.com/box/api/artifacts/download/WLTest-Helloworld-Native-Android-Gradle-App_xmd2in2athbzbudk2hd4liyr/23/app-debug.apk?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c
Resolving osm4-rhmap.osm4.skunkhenry.com... 52.19.216.112
Connecting to osm4-rhmap.osm4.skunkhenry.com|52.19.216.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/vnd.android.package-archive]
Saving to: ‘app-debug.apk?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c’

app-debug.apk?token     [          <=>       ]   2.82M   455KB/s    in 5.6s    

2017-08-02 12:05:39 (513 KB/s) - ‘app-debug.apk?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c’ saved [2955042]

ali@Alis-MacBook-Pro:/tmp$ wget https://osm4-rhmap.osm4.skunkhenry.com/box/api/artifacts/ota/67f91c73-f44c-4ff1-8ffa-5cc925166f5e?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c
--2017-08-02 12:05:46--  https://osm4-rhmap.osm4.skunkhenry.com/box/api/artifacts/ota/67f91c73-f44c-4ff1-8ffa-5cc925166f5e?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c
Resolving osm4-rhmap.osm4.skunkhenry.com... 52.19.216.112
Connecting to osm4-rhmap.osm4.skunkhenry.com|52.19.216.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/vnd.android.package-archive]
Saving to: ‘67f91c73-f44c-4ff1-8ffa-5cc925166f5e?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c’

67f91c73-f44c-4ff1-     [                <=> ]   2.82M   716KB/s    in 4.2s    

2017-08-02 12:05:51 (693 KB/s) - ‘67f91c73-f44c-4ff1-8ffa-5cc925166f5e?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c’ saved [2955042]
```

Artifacts listed fine:
```
ali@Alis-MacBook-Pro:/tmp$ fhc artifacts --app=xmd2in2athbzbudk2hd4liyr
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Platform    ┃ App Version ┃ Date                    ┃ Type  ┃ Credential ┃ Url                                                                                                                                              ┃
┣━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━╋━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ android     ┃ 33          ┃ 2017-08-02 09:03:10:049 ┃ debug ┃            ┃ https://osm4-rhmap.osm4.skunkhenry.com/box/api/artifacts/ota/67f91c73-f44c-4ff1-8ffa-5cc925166f5e?token=483d6e49d30e0d1e5a49262a2eb8b86df4fa334c ┃
┣━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━╋━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```


@wei-lee the my qr code scanning app was not able read the qr code generated. I use this: https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en

**Comment by aliok** [comment]
@wei-lee just one comment... Can we make the "tag" parameter mandatory? I was not using it initially and was getting weird errors. Is there a case where that tag is not required?

**Comment by wei-lee** [comment]
@aliok yes, I will make it mandatory on the server side.

**Comment by camilamacedo86** [comment]
@wei-lee I think we already did this as mandatory in the past and we had a lot of complaints about it because of if the customer doesn't define the tag should be the next available. So, I think it is perfect in this way :-) Just the sonar issues, but this command at some moment will be moved anyway to the V3 standard and we can try to fix the sonar issue there. 

Cool work :-)

**Comment by wei-lee** [comment]
@camilamacedo86 right, cool. I think I should be able to fix that.

**Comment by wei-lee** [comment]
@camilamacedo86 I have updated millicore so that the next available tag will be used if it's not provided. See https://github.com/fheng/millicore/pull/947

**Comment by fh-qube** [comment]
SonarQube analysis reported 2 issues:
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Function has a complexity of 24 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/7e67ac710248886a2fa6874c44ab78b94d46cdae/lib/cmd/common/build.js#L192) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
* MINOR [Function has a complexity of 23 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/7e67ac710248886a2fa6874c44ab78b94d46cdae/lib/cmd/common/build.js#L194) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

**Comment by camilamacedo86** [comment]
@wei-lee fantastic !!!!

**Comment by fh-qube** [comment]
SonarQube analysis reported 2 issues:
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Function has a complexity of 24 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/abfadfbece6e412d23c65a1f49b7e0d241138e01/lib/cmd/common/build.js#L192) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
* MINOR [Function has a complexity of 23 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/abfadfbece6e412d23c65a1f49b7e0d241138e01/lib/cmd/common/build.js#L194) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

**Comment by fh-qube** [comment]
SonarQube analysis reported 2 issues:
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Function has a complexity of 23 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/9974b7804aa6d1bb597f8c4a4aeb40df08c8c09a/lib/cmd/common/build.js#L194) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
* MINOR [Function has a complexity of 24 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/9974b7804aa6d1bb597f8c4a4aeb40df08c8c09a/lib/cmd/common/build.js#L192) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

**Comment by fh-qube** [comment]
SonarQube analysis reported 2 issues:
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MINOR [Function has a complexity of 24 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/721bbb56d2bebd065cce2a69b31da5411c0daaa2/lib/cmd/common/build.js#L192) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)
* MINOR [Function has a complexity of 23 which is greater than 20 authorized.](https://github.com/feedhenry/fh-fhc/blob/721bbb56d2bebd065cce2a69b31da5411c0daaa2/lib/cmd/common/build.js#L194) [rule](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AFunctionComplexity)

**Pull request merged**
