### PR TITLE
Openshift mbaas type support & deprecate deploy targets cmd

### PR DESCRIPTION
**Pull request by cianclarke**

### CODE REVIEW

**Comment by wtrocki** [comment]
@cianclarke Looks like stale PR. Is this still valid?

**Comment by fheng-build-servers** [comment]
@david-martin @cianclarke please review this PR.

**Comment by fheng-build-servers** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by cianclarke** [comment]
@david-martin Did changes to deprecate deploy-targets and add support for mBaaS target admin land elsewhere? 
If not @wtrocki this may not be stale, just fell beneath the back of the desk or something :-)

**Comment by david-martin** [comment]
mbaas create/update has already landed on master fhc.
Closing this PR based on that, and we don't want to remove deploy targets functionality (possibly still being used in older fh2 cluster). We could deprecate it, but removing it is too big a jump

**Pull request closed without merging**
