### PR TITLE
RHMAP-17073 - fhc requires /refs/head/<Branchname> rather than just t…

### PR DESCRIPTION
**Pull request by camilamacedo86**
*Motivation*

Fix bug related to $fhc app create via the branch name.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@camilamacedo86 After a quick review of the change it looks good, i will do some verification on Monday

**Comment by camilamacedo86** [comment]
@laurafitzgerald thank you for a check. I am looking for your review. :-)

**Comment by laurafitzgerald** [comment]
**Verification**
- Installed fhc version associated with this branch.
- Created new project on [oms2](https://rhmap.osm2.skunkhenry.com/#projects/c7w4wtjusmyi34u2obvozggn/apps)
- Ran command below
```
fhc app create --project=c7w4wtjusmyi34u2obvozggn --title=MyNewApp --type=cloud_nodejs --repo=https://github.com/feedhenry-templates/helloworld-ios.git --branch=master
```
I also noticed that the clone doesn't work when using ssh although the [command help](https://github.com/feedhenry/fh-fhc/blob/master/lib/cmd/fh3/app/create.js#L15) implies that it can be used. I would recommend updating this and also removing the reference to `refs/head` from the help there too. :)

The code change is verified. :) Thanks @camilamacedo86

**Comment by laurafitzgerald** [comment]
@camilamacedo86  any reason you closed this?

**Comment by camilamacedo86** [comment]
@laurafitzgerald sorry it was a mistake.

**Comment by laurafitzgerald** [comment]
@camilamacedo86 ah okay. Let me  know if you have any questions about my comments that I left. :)

**Comment by camilamacedo86** [comment]
@laurafitzgerald,

tks for the review. The help command was changed, however, it doesn't have the ssh option.  Could you check if it is ok now?

**Comment by laurafitzgerald** [comment]
Looks good @camilamacedo86. changes approved. :)

**Pull request merged**
