### PR TITLE
Add a task to push/pull POT/PO files to/from the Zanata server

### PR DESCRIPTION
**Pull request by tagoh**
New task that may affects the workflow would be 'potupload'.
Once all string changes is frozen, this task would works to upload
the source strings file in the gettext format to the Zanata server,
the web-based translation platform. and can ask translators
to get it in various languages. once it has been done or time to
make a new release, 'dist' task would pulls the latest translations
from the Zanata server to include them in the release.

Note that uploading into the Zanata server requires an account on it
and zanata.ini file with the API key to automate the process.

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by tagoh** [comment]
Pulling translations on dist should be dropped perhaps, to avoid releasing not-yet-tested translations. that said someone may needs to watch the release schedule, request translators for updates against it and get it back as PR in a timely manner then. I'm not sure what is the better approach for the workflow though.

**Comment by jasonmadigan** [comment]
@tagoh would you be able to guide me through what needs to be setup (API key etc) in `~/.config/zanata.ini` to do this?

**Comment by jasonmadigan** [comment]
Have tested this locally by:

* Running `grunt zanata:pull` (I get a ENOENT for `~/.config/zanata.ini` but it continues anyway)
* Setting my `LANG` to `LANG=ja_JP.UTF-8`

**Comment by jasonmadigan** [comment]
I believe we can safely merge this. Wondering if we should checkin `po/ja.po` for distribution when this is published to npm.

**Comment by tagoh** [comment]
@jasonmadigan, you need to create an account for http://translate.zanata.org first. please take a look at http://docs.zanata.org/en/release/user-guide/account/account-sign-up/. then you can get your API key from the user settings. for more details, http://zanata-client.readthedocs.io/en/latest/configuration/ would helps you.

**Comment by jasonmadigan** [comment]
@tagoh perfect, thank you

**Comment by mmurphy** [comment]
I know the README is currently very light on instructions
but I think it would be good to get any info on this (particularly requirements) included.

**Comment by tagoh** [comment]
@mmurphy, Sure. that would be a good idea but it looks to me like README.md contains materials for users so far but not for developers or contributors. is it still a good place to mention about it?

**Comment by mmurphy** [comment]
@tagoh I'd guess that most users wouldn't see the README unless they check the registry page for it.  Most would just look from the docs.feedhenry.com pages.
There are already sections called "Extending" and "Tests" which are developer/contributor focussed.  I'd say, move those together at the bottom of the file, and add the translation requirements.  It will remind anyone that does see it that they can contribute.

**Comment by tagoh** [comment]
Okay, updated README a bit. though I still feels it is missing how to let translators know new translatable strings is available on the server and when it happens and when is the dead line to be finished. I'm sure it should be documented somewhere but not sure if it should be in README.

**Comment by jasonmadigan** [comment]
@tagoh I'd say `fheng/help` is probably the best place for a doc like that (e.g. how to let translaters know there are changes). Let me see if you have access to that repo.

**Comment by tagoh** [comment]
@jasonmadigan, sure. but it is closely relevant to the workflow. what I could suggest is to have a check point to freeze the changes for strings in the schedule and ensure no string breakage after that so translators can concentrates translating.

**Comment by jasonmadigan** [comment]
@tagoh think we're almost good to merge - can you just bump the patch version in `package.json`?

**Comment by tagoh** [comment]
@jasonmadigan, done.

**Comment by tagoh** [comment]
@jasonmadigan ping

**Comment by jasonmadigan** [comment]
@tagoh looks good, lets merge.

**Comment by wtrocki** [comment]
@tagoh - Going to revert this change as it's breaking the build for the moment on master.

**Pull request merged**
