### PR TITLE
Fix for  vulnerable dependency path

### PR DESCRIPTION
**Pull request by benmag1**
fh-fhc currently has a 2 vulnerable dependency, introducing 2 different types of known vulnerabilities.

This PR fixes one vulnerable dependency, introducing [remote memory exposure ](https://snyk.io/vuln/npm:request:20160119) vulnerability in the `request` dependency.

You can see [Snyk test report](https://snyk.io/test/github/feedhenry/fh-fhc) of this project for details. 

This PR changes `Package.json` to upgrade `request` to the newer 2.74.0 version, and will fix  the vulnerability listed above.
You can get alerts and fix PRs for future vulnerabilities for free by [watching this repo with Snyk](https://snyk.io/add).

Note this PR fixes all the vulnerabilities introduced trough `request` dependency, in order to be vulnerability free you will need to upgrade `moment` dependency as well.

Full disclosure: I'm a part of the Snyk team, just looking to spread some security goodness and awareness ;)

### CODE REVIEW

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by david-martin** [comment]
test this please

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by david-martin** [comment]
@benmag1 Probably needs an update to npm-shrinkwrap
`npm ERR! invalid: request@2.11.4 /mnt/ebs1/workspace/fh-fhc_pullrequests/node_modules/request
`

**Comment by david-martin** [comment]
@benmag1 I fixed the npm-shrinkwrap in #260 and rebased from latest master.
Will close this (I didnt' have permission to push to your fork) and merge in the dep fix in #260

**Pull request closed without merging**
