### PR TITLE
RHMAP-11108-Remove files CRUDL commands from fh-fhc

### PR DESCRIPTION
**Pull request by camilamacedo86**
JIRA: https://issues.jboss.org/browse/RHMAP-12413

Following the local test. 
```
Camilas-MacBook-Pro:fh-fhc cmacedo$ bin/fhc.js fhc files
fhc ERR! Error: Command not found: fhc
fhc ERR! 
fhc ERR! System Darwin 15.6.0
fhc ERR! command "/Users/cmacedo/.nvm/versions/node/v4.4.3/bin/node" "/Users/cmacedo/work/fh-fhc/bin/fhc.js" "fhc" "files"
fhc Command executed with error
```

### CODE REVIEW

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by aidenkeating** [comment]
retest this please

**Comment by aidenkeating** [comment]
@camilamacedo86 I'm assuming https://github.com/feedhenry/fh-fhc/pull/302 can be closed in place of this?

**Comment by camilamacedo86** [comment]
@aidenkeating  Yes. The JIRA was duplicated.

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Pull request merged**
