### PR TITLE
Fix of assert in test_environment.js file

### PR DESCRIPTION
**Pull request by trepel**
Motivation: I tried to run `grunt test` but I was getting error:

Uncaught exception:  'AssertionError: undefined == 'testTarget1'

After this change it has gone.

### CODE REVIEW

**Comment by trepel** [comment]
retest this please

**Comment by wtrocki** [comment]
Retest this please

**Comment by wtrocki** [comment]
What node version you using?

**Comment by wtrocki** [comment]
Grunt test works fine. I must be problem with your version. Closing as outdated.

**Pull request closed without merging**
