### PR TITLE
Fixed the commands documentation so that is now clear that the environment parameter is the environment ID and not the environment label.

### PR DESCRIPTION
**Pull request by ziccardi**

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@ziccardi this looks good - looks like master has moved on, so will need to be rebased:

```
git fetch --all && git rebase upstream/master
```

**Comment by ziccardi** [comment]
ping @wtrocki @paolobueno @odra 
@rsmeral

**Comment by wei-lee** [comment]
LGTM. Perhaps update the version number in sonar-project.properties file as well.

**Comment by wtrocki** [comment]
LGTM. Feel free to merge and publish version to npm.

**Comment by wtrocki** [comment]
Published to NPM

**Pull request merged**
