### PR TITLE
Fix display of git url in apps list - FHCLI-1

### PR DESCRIPTION
**Pull request by mmurphy**

### CODE REVIEW

**Comment by cianclarke** [comment]
Hi Martin - reviewed, looks good. Can you port this small change to the `beta` branch when you get the chance?
Cheers
Cian

**Comment by fheng-build-servers** [comment]
[FAILURE] A build relating to [Ticket #FHCLI-1](https://issues.jboss.org/browse/FHCLI-1) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/1/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/1/)

**Comment by fheng-build-servers** [comment]
[FAILURE] A build relating to [Ticket #FHCLI-1](https://issues.jboss.org/browse/FHCLI-1) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/2/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/2/)

**Comment by fheng-build-servers** [comment]
[FAILURE] A build relating to [Ticket #FHCLI-1](https://issues.jboss.org/browse/FHCLI-1) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/3/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/3/)

**Comment by fheng-build-servers** [comment]
[SUCCESS] A build relating to [Ticket #FHCLI-1](https://issues.jboss.org/browse/FHCLI-1) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/4/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/4/)

**Comment by fheng-build-servers** [comment]
[SUCCESS] A build relating to [Ticket #FHCLI-1](https://issues.jboss.org/browse/FHCLI-1) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/5/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/5/)

**Pull request closed without merging**
