### PR TITLE
RHMAP-4361 - Fix http proxy support in fhc

### PR DESCRIPTION
**Pull request by shannonmpoole**
fhc target command does not work when using a http proxy 

While doing this: check that other commands work (prob check that all calls to request module) are correctly using proxy

### CODE REVIEW

**Comment by shannonmpoole** [comment]
So this was difficult to test locally. I had trouble getting an https compatible proxy up and running so some commands failed as expected. But it was clear that the commands we're using the proxy. Please review carefully.

**Comment by shannonmpoole** [comment]
@cianclarke and @wei-lee can you please review this?

**Comment by wei-lee** [comment]
LGTM

**Comment by mmurphy** [comment]
@shannonmpoole and @wei-lee Shouldn't the sonarqube PR analysis be required to pass here?

**Comment by wei-lee** [comment]
retest this please

**Comment by wei-lee** [comment]
@mmurphy  sonarqube was broken. Not it was failed.

**Pull request merged**
