### PR TITLE
RHMAP-14888 - Link into npm page of FHC Cli tool to the repository is…

### PR DESCRIPTION
**Pull request by camilamacedo86**
JIRA : https://issues.jboss.org/browse/RHMAP-14888

### CODE REVIEW

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by aidenkeating** [comment]
retest this please

**Comment by camilamacedo86** [comment]
@aidenkeating tks added :-)

**Comment by camilamacedo86** [comment]
retest this please

**Comment by aidenkeating** [comment]
retest this please

**Comment by aidenkeating** [comment]
@camilamacedo86 Made a review PR here around the formatting of the `repository` field. Also, this needs to be rebased. https://github.com/camilamacedo86/fh-fhc/pull/1

**Comment by camilamacedo86** [comment]
retest this please

**Comment by aidenkeating** [comment]
retest this please

**Comment by pb82** [comment]
retest this please

**Pull request merged**
