### PR TITLE
Fh v3.6.1

### PR DESCRIPTION
**Pull request by jasonmadigan**

### CODE REVIEW

**Comment by fheng-build-servers** [comment]
@david-martin @cianclarke please review this PR.

**Comment by fheng-build-servers** [comment]
### Pull Request Review Checklist

- [x] Make a change, submit a PR
- [ ] Passing CI build
- [ ] Component version has been bumped appropriately in accordance with [semver](http://semver.org/)
- [ ] Ensure base branch is correct - e.g. `FH-vX.X.X` for release fixes or `master`
- [ ] Dependencies have locked-down versions - no `~` or `^` in `package.json`, please
- [ ] Ensure shrinkwrap file, `npm-shrinkwrap.json`, is updated if dependencies have changed
- [ ] Changelog entry
- [ ] fhcap pull-request
  - [ ] Passing CI build
  - [ ] Cookbooks updated with new component versions
  - [ ] PR created back to `master` for future release, or specific release branch e.g. `FH-v3.6.0`
  - [ ] Cookbooks updated with any component config changes
- [ ] Changes deployed and tested in a staging area using `fhcap-cli` (provide a link)
- [ ] Link to `fh-uart` test run
- [ ] JIRA updates
  - [ ] Appropriate fixVersion
  - [ ] "Fix RC Version" set if this is a fix for a release branch (e.g. `FH-v3.x.x`)
  - [ ] Links to this PR and fhcap PR in the JIRA
  - [ ] Tester notes for reproduction/verfication
  - [ ] Deployment notes, if applicable

**Comment by jasonmadigan** [comment]
Previously reviewed in other PRs. Publishing to npm now. Will be tagged as `latest-2`, so users would need to explicitly install this version to get its changes.

**Comment by jasonmadigan** [comment]
```
+ fh-fhc@2.1.0
```

**Pull request merged**
