### PR TITLE
Wait for filewritestream finish before calling callback in filedownl…

### PR DESCRIPTION
**Pull request by mmurphy**
…oad - RHMAP-3085

do not merge, needs review, tests, error case checks

### CODE REVIEW

**Comment by fheng-build-servers** [comment]
@cianclarke @jasonmadigan please review this PR.

**Comment by wtrocki** [comment]
Using `once` here is really good idea since finish event may be triggered differently depending on node version. 

Reviewed. Approved. Changed tested by QA.  Unit tests will be added as part of separate ticket. 
Please merge and integrate code into master.

**Comment by wtrocki** [comment]
@mmurphy Can You push this branch to upstream as well. I will integrate this into master. Thanks :+1:

**Comment by mmurphy** [comment]
closing this, since it was superseded by #158

**Pull request closed without merging**
