### PR TITLE
RHMAP-11670 - Remove the command  files list <APPID> from FHC tool

### PR DESCRIPTION
**Pull request by camilamacedo86**
JIRA: https://issues.jboss.org/browse/RHMAP-11670

Following local test. 

```
Camilas-MBP:fh-fhc cmacedo$ bin/fhc.js files
fhc ERR! Usage:
fhc ERR! 
fhc ERR! fhc files read <file-id>
fhc ERR! fhc files update <app-id> <file-id> <file>
fhc ERR! fhc files create <app-id> <path> <name> <fileType>
fhc ERR! fhc files delete <app-id> <file-id> <path> <name> <fileType>
fhc Command executed with error
```

### CODE REVIEW

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by aidenkeating** [comment]
retest this please

**Comment by camilamacedo86** [comment]
retest this please

**Comment by aidenkeating** [comment]
retest this please

**Comment by camilamacedo86** [comment]
All commands were removed into the https://github.com/feedhenry/fh-fhc/pull/306.

**Pull request closed without merging**
