### PR TITLE
RHMAP-15723 - Add command `fhc clone` to V3 standard

### PR DESCRIPTION
**Pull request by camilamacedo86**
JIRA: https://issues.jboss.org/browse/RHMAP-15723

Following the changes made.
* Add it to the V3 standard
* Remove call to use the V2 command. Use the same command but V3 
* Fix output
* Fix description test of the `fhc app read` command which is used here. 

Following local tests

Test when the clone is made.
`````
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js clone invchzzwmwnpwehmy54roimi invchzy3wemcaef2lokcayzd 
(node) sys is deprecated. Use util instead.
Cloning into 'TestAllHello-Cloud-App'...
##########################################################################
# THIS SYSTEM IS RESTRICTED TO AUTHORIZED USERS FOR AUTHORIZED USE ONLY. #
# UNAUTHORIZED ACCESS IS STRICTLY PROHIBITED AND MAY BE PUNISHABLE UNDER #
# THE COMPUTER FRAUD AND ABUSE ACT OF 1986 OR OTHER APPLICABLE LAWS.     #
# IF NOT AUTHORIZED TO ACCESS THIS SYSTEM, DISCONNECT NOW.               #
# BY CONTINUING, YOU CONSENT TO YOUR KEYSTROKES AND DATA CONTENT BEING   #
# MONITORED. ALL PERSONS ARE HEREBY NOTIFIED THAT THE USE OF THIS SYSTEM #
# CONSTITUTES CONSENT TO MONITORING AND AUDITING.                        #
##########################################################################

Camilas-MacBook-Pro:fh-fhc cmacedo$ 
``````
Test when the app was already cloned.
``````
Camilas-MacBook-Pro:fh-fhc cmacedo$ ./bin/fhc.js clone invchzzwmwnpwehmy54roimi invchzy3wemcaef2lokcayzd 
(node) sys is deprecated. Use util instead.
fhc ERR! Error: Command failed: /bin/sh -c git clone git@git.us.feedhenry.com:support/TestAllHello-Cloud-App.git -b master
fhc ERR! fatal: destination path 'TestAllHello-Cloud-App' already exists and is not an empty directory.
fhc ERR! 
fhc ERR! 
fhc ERR! System Darwin 15.6.0
fhc ERR! command "/Users/cmacedo/.nvm/versions/node/v4.4.3/bin/node" "/Users/cmacedo/work/fh-fhc/bin/fhc.js" "clone" "invchzzwmwnpwehmy54roimi" "invchzy3wemcaef2lokcayzd"
fhc Command executed with error
`````

### CODE REVIEW

**Comment by maleck13** [comment]
@camilamacedo86 am I right in thinking that this command just clones the app? Do we really need this command. Wondering if it wasn't working perhaps it would be better to remove it?

**Comment by camilamacedo86** [comment]
Hi, @maleck13  Thanks abou the review. Following some points. 

About the : 
"@camilamacedo86 this looks fine. Do we want to fix the depreciated output?
(node) sys is deprecated. Use util instead.
"

It shows in all commands if we will fixed need be for all. It is not the goal here. 

About the:
"@camilamacedo86 am I right in thinking that this command just clones the app? Do we really need this command. Wondering if it wasn't working perhaps it would be better to remove it?"

If we remove this command we need remove the `$fh project clone` either.  How can decide if we can remove this command? The both commands can be solved by git. However, should we keep or remove the both functionalities?

**Comment by david-martin** [comment]
@camilamacedo86 @maleck13 I don't see the benefit of the command as the user needs git installed to do it anyways. A developer is more likely to use the git cli to clone things.
However, maybe its useful to get the git urls for all apps in a project?
I see no problem with merging it if users are going to find it useful.
If there isn't use, I'd prefer for it to be removed in favour of focusing on commands that interact with platform feature APIs.

So, @camilamacedo86 is there a valid use for the command for users?

**Comment by camilamacedo86** [comment]
@david-martin I think it is more useful when the user want clone the project where this command is used too. Because for clone all project by git is required clone all project one by one. So, my vote is in keeping it is a facility any way.

**Comment by david-martin** [comment]
@camilamacedo86 lets merge this so

**Pull request merged**
