### PR TITLE
RHMAP-3131 Several fhc app commands have incorrect examples

### PR DESCRIPTION
**Pull request by rsmeral**

### CODE REVIEW

**Comment by fheng-build-servers** [comment]
@cianclarke @david-martin please review this PR.

**Comment by wtrocki** [comment]
Approved. Rebase needed. @rsmeral - You can mention me in PR's speed up review process.

**Comment by rsmeral** [comment]
@wtrocki Thanks for review, rebased. I guess it would be best if we set up your name as the default for fh-fhc then, right? IIRC, @david-martin can help with that.

**Comment by wtrocki** [comment]
Thanks for response. Merging changes back to master. I will bump version directly on master branch.

**Pull request merged**
