### PR TITLE
RHMAP-15404 - Fixed Main Style Errors

### PR DESCRIPTION
**Pull request by camilamacedo86**
JIRA: - https://issues.jboss.org/browse/RHMAP-15404https://issues.jboss.org/browse/RHMAP-15404

- If statements in the same line
- Space between function name and ()
- Space catch 
- Space for
- indent spaces
- const

### CODE REVIEW

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by pb82** [comment]
retest this please

**Comment by camilamacedo86** [comment]
@grdryn Could you approve this one?

**Comment by grdryn** [comment]
@camilamacedo86 unfortunately I don't have time to go through this one at the moment. @pb82 maybe you or someone from your team would be able to take this on?

**Comment by pb82** [comment]
@camilamacedo86 Those are formatting fixes so it should be ok. I didn't review all of the changes but checked some random samples and they look fine (mostly whitespace and brackets).

**Comment by pb82** [comment]
needs a rebase, otherwise looks good

**Pull request merged**
