### PR TITLE
 🔥 [WIP] deprecate fhc build command

### PR DESCRIPTION
**Pull request by wei-lee**
# Jira link(s)

https://issues.jboss.org/browse/RHMAP-21611

# What

Deprecate the fhc build command

# Why

The build farm service will be retired by the end of the year, and we don't want users to be able to invoke build from fhc anymore.

# How

Change the fhc build command implementation to just print out an error message

# Verification Steps

Run fhc build and it should print out an error message

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@wei-lee if we merge it the user will be not able to call the command. Should not be added a note as was done here https://github.com/feedhenry/fh-fhc/commit/67f9b22886782b931ef787cd04e62370b20d5846 for example and then remove the command or do as you did here when the BF be not so long available?

**Comment by wei-lee** [comment]
@camilamacedo86 it's not for 4.7 release I believe. I am following the JIRA here: https://issues.jboss.org/browse/RHMAP-21619. We can discuss when this change should be published.

**Comment by camilamacedo86** [comment]
@wei-lee 

I believe that until RHMAP on the 31st December 2018 we cannot merge/publish it. Now, we can do as was done [here](https://github.com/feedhenry/fh-fhc/commit/67f9b22886782b931ef787cd04e62370b20d5846) for example. Is it make sense?

**Comment by wei-lee** [comment]
@camilamacedo86 yeah, I don't plan to release this soon TBH. I will get confirmation from @ciaran-byrne about the plan here.

**Comment by ciaran-byrne** [comment]
@camilamacedo86 good catch. Can we merge this after 4.7 is released, and we will only publish on the 31st December. Alternatively we can go ahead and deprecate the commands; @wei-lee will the studio property of "buildfarm.enabled" still be effective here? When we set that property to false on the 31st December, will all the versions of fhc just not build regardless (as we are changing the API call?)

**Comment by wei-lee** [comment]
@ciaran-byrne yes, that's correct. The API will block all the build requests anyway, so we don't really gain anything by removing it from fh-fhc. I think maybe adding the deprecation notice is enough? We can then release a new version next year to remove it completely, but I think that's optional.

**Comment by camilamacedo86** [comment]
Hi @wei-lee and @ciaran-byrne 

> 
Can we merge this after 4.7 is released, and we will only publish on the 31st December. 

IMHO no. Following the reasons:
- It is more like we publish fh-fhc with the release of 4.8 which will before this date. 
- The publications of fh-fhc don't need follow RHMAP releases and if for any reason be required to do a publication it will introduce a bug since the users are entitled to use until  31st December.
- This command is used for many users and if this change is performed before the time will make raining support cases. :-P

My suggestion: 
- We could merge now just a DEPRECATION NOTE in the command as for auth commands see done [here](https://github.com/feedhenry/fh-fhc/commit/67f9b22886782b931ef787cd04e62370b20d5846) in order to make clear and notify them about this. 
- We can keep the PR but just approve and merge it near 31st December with the planned date to publish this change.

**Comment by camilamacedo86** [comment]
@wei-lee I done it here : https://github.com/feedhenry/fh-fhc/pull/457

**Pull request closed without merging**
