### PR TITLE
Added Audit Logs To Environment Data Sources

### PR DESCRIPTION
**Pull request by nialldonnellyfh**

### CODE REVIEW

**Comment by fh-automatron** [comment]
@jasonmadigan @maleck13 please review this PR.

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* A component owner should review your change (we've tagged these above)
* This change should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* Ensure JIRA is up to date (e.g. deployment notes, tester notes, fix version, release notes)
* There should be an associated fhcap PR with this change - please provide a link to this
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.

**Comment by nialldonnellyfh** [comment]
@david-martin Small fhc PR to go with the audit log functionality if you get a min.

**Comment by david-martin** [comment]
Reviewed.
Do you have sample commands to run against your cluster to exercise the new option?

**Comment by nialldonnellyfh** [comment]
Sorry, yes. It is published to npm.skunkhenry.com (http://npm.skunkhenry.com/fh-fhc/-/fh-fhc-2.3.0-121.tgz) 

If you target http://testing.ndonnelly.skunkhenry.com and run

fhc appforms environments data-sources audit-logs --id 565d9e00993ed21e5a0d9f94 --env dev

it will display a table of updates.

**Comment by david-martin** [comment]
@nialldonnellyfh I get this error
```
[dmartin@rollins-tp fhcap]$ fhc version
FHC Version: 2.3.0-121 (Up to date)
FeedHenry Product Version: 3
FeedHenry Platform Version: 3.7.0
[dmartin@rollins-tp fhcap]$ fhc appforms environments data-sources audit-logs --id 565d9e00993ed21e5a0d9f94 --env dev
fhc ERR! Error: Command not found: audit-logs
fhc ERR! 
fhc ERR! System Linux 4.2.3-300.fc23.x86_64
fhc ERR! command "node" "/home/dmartin/.nvm/v0.10.41/bin/fhc" "appforms" "environments" "data-sources" "audit-logs" "--id" "565d9e00993ed21e5a0d9f94" "--env" "dev"
fhc Command executed with error
```

**Comment by nialldonnellyfh** [comment]
@david-martin Sorry, I linked to the wrong fhc build. It should have been (http://npm.skunkhenry.com/fh-fhc/-/fh-fhc-2.3.0-126.tgz) instead of (http://npm.skunkhenry.com/fh-fhc/-/fh-fhc-2.3.0-121.tgz)

**Comment by david-martin** [comment]
```
[dmartin@rollins-tp fhcap]$ fhc version
FHC Version: 2.3.0-126 (Up to date)
FeedHenry Product Version: 3
FeedHenry Platform Version: 3.7.0
[dmartin@rollins-tp fhcap]$ fhc appforms environments data-sources audit-logs --id 565d9e00993ed21e5a0d9f94 --env dev
Usage:
 fhc appforms environments data-sources audit-logs --environment=<environment> --id=<id>

Examples:
  fhc appforms environments data-sources audit-logs --environment="dev" --id="datasource1234"    Read a single data source, including Audit Logs deployed to an environment.


Options:
  --environment  ID of environment to read data source data from  [required]
  --id           ID of the data source to read                    [required]

Missing required arguments: environment
fhc ERR! Error: Missing required arguments: environment
fhc ERR! 
fhc ERR! System Linux 4.2.3-300.fc23.x86_64
fhc ERR! command "node" "/home/dmartin/.nvm/v0.10.41/bin/fhc" "appforms" "environments" "data-sources" "audit-logs" "--id" "565d9e00993ed21e5a0d9f94" "--env" "dev"
fhc Command executed with error
[dmartin@rollins-tp fhcap]$ fhc appforms environments data-sources audit-logs --id 565d9e00993ed21e5a0d9f94 --environment dev
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Service ID               ┃ Service Name     ┃ Endpoint ┃ Status ┃ Error                 ┃ Data Length ┃ Data Hash                                ┃ Refresh Timestamp ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━╋━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━┫
┃ icidpdvbwq622yfrzfs7sdxv ┃ testmongoservice ┃ /assets  ┃ ok     ┃ NONE                  ┃ 8           ┃ 81e23e111626653ac95e2645d47024f0ca2d9a90 ┃ a minute ago      ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━╋━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━┫
┃ icidpdvbwq622yfrzfs7sdxv ┃ testmongoservice ┃ /assets  ┃ ok     ┃ NONE                  ┃ 8           ┃ 81e23e111626653ac95e2645d47024f0ca2d9a90 ┃ 2 minutes ago     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━╋━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━┫
┃ icidpdvbwq622yfrzfs7sdxv ┃ testmongoservice ┃ /assets  ┃ ok     ┃ NONE                  ┃ 8           ┃ 81e23e111626653ac95e2645d47024f0ca2d9a90 ┃ 4 minutes ago     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━╋━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━┫

````

Should I be concerned about the number of entries? (~700)
Is a table the best view for this?

**Comment by nialldonnellyfh** [comment]
Maybe show the last 20 ? Depending on the frequency of updates for the data source, there could be a lot. 

The number of saved audit logs is configurable by the user.

**Comment by nialldonnellyfh** [comment]
@david-martin Added an option to limit the number of logs displayed when displaying a table. Does that seem reasonable?

**Comment by david-martin** [comment]
@nialldonnellyfh sounds good

**Pull request merged**
