### PR TITLE
RHMAP-5096 - Inconsistency in service ids in fh-ngui and fh-fhc

### PR DESCRIPTION
**Pull request by camilamacedo86**
JIRA: https://issues.jboss.org/browse/RHMAP-5096

Following local test.

screen shot 2017-05-08 at 2 42 23 pm

*Steps to Test*
- Go to RHMAP studio and create a new Service into  `Services & APIs>>New Service / Provision MBaaS Service/API`
- Run fhc services 

The ID in the result should be the same into RHMAP studio.

### CODE REVIEW

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by fh-automatron** [comment]
Can one of the admins verify this patch?

**Comment by wei-lee** [comment]
@camilamacedo86 This PR works, however, the problem is that after running `fhc services`, now I can't use the service id returned to read services.

So if i use the service id returned in this PR, and run 

```
fhc services read <service id>
```

I will get an error:

```
fhc ERR! Error: Error - not 2xx status code. (404)
fhc ERR! {"message":"project not found","status":"error","result":null}
fhc ERR! Request ID:  74f3ae4e-93a3-4525-b8e4-efdfca08dce4
```

So after reading the ticket again, I think we should either:

* show the project id as `service id` in fh-ngui
or
* allow read services with the app GUID.

Does this make sense?

**Comment by camilamacedo86** [comment]
@wei-lee tks for the review. I will make these changes.

**Comment by camilamacedo86** [comment]
For this request was decided won't fix.
"The thing is that other fhc services commands expect service project id not service app id (which is shown in studio). I'm sorry, but I did not notice this when I was creating this issue. So I thing this issue can be closed as won't do."

**Pull request closed without merging**
