### PR TITLE
Use grunt-fh-build to clean up Gruntfile.js

### PR DESCRIPTION
**Pull request by grdryn**

### CODE REVIEW

**Comment by fheng-build-servers** [comment]
[SUCCESS] A build relating to [Ticket #FH-164](https://issues.jboss.org/browse/FH-164) has just completed: [http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/29/](http://bob.feedhenry.net:8080/job/fh-fhc_pullrequests/29/)

**Comment by fheng-build-servers** [comment]
@cianclarke @maleck13 please review this PR.

**Comment by grdryn** [comment]
I think that grunt-fh-build should be released under a free software license before this is merged.

**Comment by wtrocki** [comment]
@grdryn grunt-fh-build was released under [apache license](https://github.com/feedhenry/grunt-fh-build/blob/master/LICENSE). 

I have some automation and testing work planed on fh-fhc and grunt-fh-build. Can l just include and test Your changes as part of new PR?

**Comment by wtrocki** [comment]
Merge back to master. More work to be done as separate ticket.

**Pull request merged**
