### PR TITLE
Remove zanata changes 

### PR DESCRIPTION
**Pull request by wtrocki**
# Motivation

Zatana changes are breaking build, prevents numerous PR's from being merged. 
Removing them for now. 

@tagoh @jasonmadigan - Feel free to reopen ticket, provide better implementation for this. 
It looks like we aren't able to call zatana translation service and build is timing out. 

Reverting this PR:
https://github.com/feedhenry/fh-fhc/pull/217

### CODE REVIEW

**Comment by wtrocki** [comment]
@corinnekrych - Can you review and rebase your PR after this is merged?

**Comment by corinnekrych** [comment]
+1

**Comment by tagoh** [comment]
There seems a bug in grunt-zanata-js that introduced this. fixed it there. will submit another PR to revert this.

**Comment by tagoh** [comment]
submitted as https://github.com/feedhenry/fh-fhc/pull/291

**Pull request merged**
