### PR TITLE
RHMAP-5465 - i18n support for fhc help

### PR DESCRIPTION
**Pull request by tagoh**
"fhc help" is capable to show the markdown docs if any but it isn't able to localize. this PR allows us to translate markdown docs, generate the translated, and show them on "fhc help".

### CODE REVIEW

**Comment by jasonmadigan** [comment]
@tagoh code looks fine - wondered if there's something I should be running here to verify the change?

**Comment by tagoh** [comment]
@jasonmadigan Thank you for the review. I didn't add the localized markdown files into the change because there are no translations so far in the Zanata yet. so for testing, if you put something under doc/languages/ja/*, e.g. doc/languages/ja/fhc/help.md and with some changes to see the difference, then run "LANG=ja_JP.UTF-8 ./bin/fhc.js help help" say, you'll see if it works properly or not.

**Comment by tagoh** [comment]
Oh, and also good to try "grunt updatetrans" to see if the task can creates the localized markdown from POs.

**Comment by camilamacedo86** [comment]
Hi @tagoh, 

I'm trying to test it. Following the tests so far. 

The command `$ grunt updatetrans` worked fine.

```

Camilas-MacBook-Pro:fh-fhc cmacedo$ grunt updatetrans
Running "zanata:pull_fhc" (zanata) task
>> Downloaded into po/ja.po

Running "zanata:pull_help" (zanata) task

Running "gettext-markdown:po2md" (gettext-markdown) task

Done, without errors.


Execution Time (2017-05-24 05:43:03 UTC)
loading tasks         2.2s  ▇▇▇ 1%
zanata:pull_fhc   1m 17.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 50%
zanata:pull_help    1m 16s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 49%
Total 2m 36.1s

Camilas-MacBook-Pro:fh-fhc cmacedo$ 

```
However, the markdown I am not sure how we should test. I couldn't find "doc/languages/ja/*". Could you describe better it? Also, we have a JIRA to remove the docs/ https://issues.jboss.org/browse/RHMAP-9451. Is it in the same place?

**Comment by tagoh** [comment]
@camilamacedo86 Oops, sorry. well, the markdown for languages which isn't available in po won't be generated by the task.
So I've updated a bit in Zanata to get a few strings translated. try it again. you'll see ja.po for "help" downloaded and then the markdown files for ja during "updatetrans" task.

**Comment by tagoh** [comment]
looking at https://issues.jboss.org/browse/RHMAP-9451, apparently it affects this ticket too. we should close this then?

**Comment by camilamacedo86** [comment]
@jasonmadigan @kpiwko We need a help here to check if this JIRA : https://issues.jboss.org/browse/RHMAP-9451 is for be done or not. Because if it this jira is for be done this PR should be closed.

**Comment by camilamacedo86** [comment]
@tagoh I am closing this PR in prol of the JIRA : https://issues.jboss.org/browse/RHMAP-9451. According to @david-martin the docs should be removed.

**Pull request closed without merging**
